packages: []

catalogs:
  cli:
    '@anolilab/semantic-release-preset': ^12.1.2
    pncat: ^0.7.7
    semantic-release: ^25.0.2
    taze: ^19.9.2
  dev:
    audit-ci: ^7.1.0
    conventional-changelog-conventionalcommits: 9.1.0
    is-ci: ^4.1.0
    renovate: 42.64.1
    sort-package-json: ^3.6.0
  lint:
    '@anolilab/commitlint-config': ^7.0.0
    '@anolilab/lint-staged-config': ^4.0.0
    '@anolilab/prettier-config': ^6.0.8
    '@anolilab/textlint-config': ^9.0.9
    '@commitlint/cli': ^20.2.0
    '@commitlint/config-conventional': ^20.2.0
    '@secretlint/secretlint-rule-preset-recommend': ^11.2.5
    husky: ^9.1.7
    lint-staged: ^16.2.7
    prettier: ^3.7.4
    secretlint: 11.2.5
    textlint: ^15.4.1

onlyBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - pncat
  - protobufjs
  - re2

overrides:
  chrono-node@<2.2.4: '>=2.2.4'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  tar@=7.5.1: '>=7.5.2'
  tmp@<=0.2.3: '>=0.2.4'
