packages: []

catalogs:
  cli:
    '@anolilab/semantic-release-preset': ^11.0.4
    pncat: ^0.5.4
    semantic-release: ^24.2.9
    taze: ^19.7.0
  dev:
    audit-ci: ^7.1.0
    conventional-changelog-conventionalcommits: 9.1.0
    is-ci: ^4.1.0
    renovate: 41.123.0
    sort-package-json: ^3.4.0
  lint:
    '@anolilab/commitlint-config': ^6.0.3
    '@anolilab/lint-staged-config': ^3.0.31
    '@anolilab/prettier-config': ^6.0.4
    '@anolilab/textlint-config': ^9.0.5
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@secretlint/secretlint-rule-preset-recommend': ^11.2.4
    husky: ^9.1.7
    lint-staged: ^16.2.1
    prettier: ^3.6.2
    secretlint: 11.2.4
    textlint: ^15.2.2

onlyBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - pncat
  - protobufjs
  - re2

overrides:
  chrono-node@<2.2.4: '>=2.2.4'
  tmp@<=0.2.3: '>=0.2.4'
