packages: []

catalogs:
  cli:
    '@anolilab/semantic-release-preset': ^11.0.4
    pncat: ^0.7.3
    semantic-release: ^25.0.1
    taze: ^19.8.1
  dev:
    audit-ci: ^7.1.0
    conventional-changelog-conventionalcommits: 9.1.0
    is-ci: ^4.1.0
    renovate: 42.11.0
    sort-package-json: ^3.4.0
  lint:
    '@anolilab/commitlint-config': ^6.0.6
    '@anolilab/lint-staged-config': ^3.0.37
    '@anolilab/prettier-config': ^6.0.7
    '@anolilab/textlint-config': ^9.0.8
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@secretlint/secretlint-rule-preset-recommend': ^11.2.5
    husky: ^9.1.7
    lint-staged: ^16.2.6
    prettier: ^3.6.2
    secretlint: 11.2.5
    textlint: ^15.2.3

onlyBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - pncat
  - protobufjs
  - re2

overrides:
  chrono-node@<2.2.4: '>=2.2.4'
  tmp@<=0.2.3: '>=0.2.4'
