packages: null

catalogs:
  cli:
    '@anolilab/semantic-release-preset': ^13.1.1
    pncat: ^0.11.1
    semantic-release: ^25.0.3
    taze: ^19.10.0
  dev:
    audit-ci: ^7.1.0
    conventional-changelog-conventionalcommits: 9.3.1
    is-ci: ^4.1.0
    renovate: 43.101.2
    sort-package-json: 3.6.1
  lint:
    '@anolilab/commitlint-config': 9.4.0
    '@anolilab/lint-staged-config': ^9.0.0
    '@anolilab/prettier-config': 9.1.1
    '@anolilab/textlint-config': 12.1.5
    '@commitlint/cli': ^20.5.0
    '@commitlint/config-conventional': ^20.5.0
    '@secretlint/secretlint-rule-preset-recommend': ^11.4.1
    husky: ^9.1.7
    lint-staged: ^16.4.0
    prettier: ^3.8.1
    secretlint: 11.4.1
    textlint: 15.5.2

onlyBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - pncat
  - protobufjs
  - re2

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  '@modelcontextprotocol/sdk@<1.25.2': '>=1.25.2'
  '@modelcontextprotocol/sdk@>=1.10.0 <=1.25.3': '>=1.26.0'
  chrono-node@<2.2.4: '>=2.9.0'
  diff@>=5.0.0 <5.2.2: '>=5.2.2'
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  fast-xml-parser@>=5.0.9 <=5.3.3: '>=5.3.4'
  glob@>=10.2.0 <10.5.0: '>=13.0.2'
  glob@>=11.0.0 <11.1.0: '>=13.0.2'
  js-yaml@<3.14.2: '>=4.1.1'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  qs@<6.14.1: '>=6.14.1'
  renovate@>=32.124.0 <42.68.5: '>=42.68.5'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tar@=7.5.1: '>=7.5.7'
  tmp@<=0.2.3: '>=0.2.5'
  undici@<6.23.0: '>=6.23.0'
  undici@>=7.0.0 <7.18.2: '>=7.18.2'
