name: "CI"

on: # yamllint disable-line rule:truthy
    push:
        paths:
            - ".github/workflows/**"
        branches:
            - "main"
    pull_request:
        paths:
            - ".github/workflows/**"
        branches:
            - "main"
            - "!v[0-9]*"

permissions:
    contents: "read"

jobs:
    lint-workflows:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911" # v2.13.0
              with:
                  egress-policy: "audit"

            - name: "Git checkout"
              uses: "actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955" # v4.3.0
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            # From https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
            - name: "Check workflow files"
              run: |
                  bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
                  ./actionlint -color -shellcheck=""
