# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Tests"

on: # yamllint disable-line rule:truthy
    push:
        branches:
            - "main"
    # eslint-disable-next-line yml/no-empty-mapping-value
    pull_request: # yamllint disable-line rule:empty-values
    merge_group: # yamllint disable-line rule:empty-values

concurrency:
    group: "ci-tests-${{ github.ref }}-1"
    cancel-in-progress: true

permissions:
    contents: "read"

jobs:
    test:
        name: "Build & Unit Test: node-23"

        runs-on: "ubuntu-latest"

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411" # v2.19.4
              with:
                  egress-policy: "audit"

            - name: "Git checkout"
              uses: "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10" # v6.0.3
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Setup resources and environment"
              id: "setup"
              uses: "anolilab/workflows/step/setup@14407443bfb6117b190ca9585a00c03cd931500e" # main
              with:
                  node-version: "24"
                  install-bun: false
                  enable-nx-cache: false
                  run-signatures-audit: false

            - name: "Test"
              run: "pnpm run test"
