name: "Zizmor"
on: # yamllint disable-line rule:truthy
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    zizmor:
        permissions:
            security-events: "write"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/zizmor.yml@b5d611c5dda8645e93f2407e3d3fee250a9f5376" # main
        with:
            min_severity: "medium"
